import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
const load = async file => import('data:text/javascript;base64,' + Buffer.from(ts.transpileModule(readFileSync(file,'utf8'), {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText).toString('base64'));
const { Joystick } = await load('app/joystick.ts');
const { Arena } = await load('app/arena.ts');
const stick = new Joystick();
assert(stick.begin(1,{x:100,y:100},{x:103,y:100}));
assert.deepEqual(stick.value,{x:0,y:0});
assert(!stick.begin(2,{x:0,y:0},{x:0,y:0}));
assert(!stick.move(2,{x:400,y:400}));
stick.move(1,{x:124.5,y:100});assert.equal(stick.value.x,.5);
stick.move(1,{x:200,y:200});assert(Math.abs(Math.hypot(stick.value.x,stick.value.y)-1)<1e-10);
assert(!stick.end(2));assert.equal(stick.pointer,1);
assert(stick.end(1));assert.deepEqual(stick.value,{x:0,y:0});assert.deepEqual(stick.knob,{x:0,y:0});
const arena=new Arena('green');arena.between=100;
arena.update(.1,new Set(),{x:.5,y:0});assert.equal(arena.player.x,562.25);
arena.update(.1,new Set(),{x:0,y:-.5});assert.equal(arena.player.y,317.75);assert.equal(arena.player.dir,'up');
let x=arena.player.x,y=arena.player.y;
arena.update(.1,new Set(['d','s']),{x:-1,y:0});assert(Math.abs(Math.hypot(arena.player.x-x,arena.player.y-y)-24.5)<1e-9);
x=arena.player.x;y=arena.player.y;arena.update(.1,new Set(),stick.value);assert.equal(arena.player.x,x);assert.equal(arena.player.y,y);
arena.update(.1,new Set([' ']),{x:1,y:0});assert(arena.player.attack>0);assert(arena.player.x>x);
stick.begin(3,{x:0,y:0},{x:44,y:0});stick.reset();assert.deepEqual(stick.value,{x:0,y:0});assert.equal(stick.pointer,null);
console.log('PASS: dead zone, analog speed, diagonal cap, pointer ownership, release/cancel/reset, keyboard priority, facing and simultaneous movement/punch.');
