'use client';
import {useState} from 'react';
import {kits,type Inventory} from './inventory';
import {characterLabel,type Dog} from './arena';
export default function Garage({inventory,dog,onBuy,onEquip,onClose,message,canShop}:{inventory:Inventory;dog:Dog;onBuy:(id:string)=>void;onEquip:(id:string)=>void;onClose:()=>void;message:string;canShop:boolean}){
 const [selected,setSelected]=useState(inventory.equipped),[action,setAction]=useState('idle');
 const kit=kits.find(k=>k.id===selected)||kits[0],owned=inventory.owned.includes(kit.id),equipped=inventory.equipped===kit.id;
 return <section className="garage" aria-label="Garage and cosmetic shop"><div className="garage-heading"><div><p className="eyebrow lime">ORBITAL OUTLAWS / COLLECTION 01</p><h1>THE GARAGE</h1></div><button className="garage-back" onClick={onClose}>← BACK TO ARENA</button></div><div className="credit-strip"><strong>{inventory.credits.toLocaleString()} GAME CREDITS</strong><span>Cosmetic preview · Shop temporarily disabled</span></div><div className="garage-layout"><div className="preview-panel" style={{'--kit-color':kit.color} as React.CSSProperties}><span className="eyebrow">{action==='idle'?'GEAR PREVIEW':'PUNCH PREVIEW'}</span><div className={`dog-preview ${action==='punch'?'punch-preview':''}`}><img style={{filter:kit.filter}} src={`/sprites/${dog}-${action}-${action==='idle'?'down':'right'}-${action==='idle'?'1':'3'}.png`} alt={`${kit.name} on ${characterLabel(dog)}`}/>{action==='punch'&&<span className="preview-arc"/>}</div><div className="preview-buttons"><button aria-pressed={action==='idle'} onClick={()=>setAction('idle')}>GEAR</button><button aria-pressed={action==='punch'} onClick={()=>setAction('punch')}>PUNCH EFFECT</button></div><h2>{kit.name}</h2><p>{kit.description}</p><p className="cosmetic-note">Colour finish + punch effect. Same health, speed and damage.</p><button className="launch" disabled={!canShop||equipped||(!owned&&inventory.credits<kit.price)} onClick={()=>owned?onEquip(kit.id):onBuy(kit.id)}>{!canShop?'SHOP TEMPORARILY DISABLED':equipped?'EQUIPPED':owned?'EQUIP KIT':inventory.credits<kit.price?`NEED ${kit.price-inventory.credits} MORE CREDITS`:`BUY FOR ${kit.price} CREDITS`}</button><p className="garage-message" role="status">{message||'Preview any kit before spending your game credits.'}</p></div><div className="collection"><h2>Choose your finish</h2><div className="kit-list">{kits.map(k=><button key={k.id} className={`kit-card ${selected===k.id?'chosen':''}`} onClick={()=>{setSelected(k.id);setAction('idle')}} aria-pressed={selected===k.id}><img src={`/sprites/${dog}-idle-down-1.png`} style={{filter:k.filter}} alt=""/><span><strong>{k.name}</strong><small>{inventory.equipped===k.id?'EQUIPPED':inventory.owned.includes(k.id)?'OWNED':`${k.price} CREDITS`}</small></span><span className="kit-swatch" style={{background:k.color}}/></button>)}</div><div className="earn-box"><h3>Preview your next look</h3><p>Explore the cosmetic finishes while playing freely. Credits and purchases are paused for now.</p><div className="garage-stats"><span><b>{inventory.runs}</b> RUNS FINISHED</span><span><b>{inventory.totalKills}</b> DOGS SMASHED</span><span><b>{inventory.owned.length}/{kits.length}</b> KITS OWNED</span></div><p className="cosmetic-note">No account or wallet is needed to play. Progress is limited to the current session.</p></div></div></div></section>
}
