'use client';
import {useEffect,useRef,useState} from 'react';
import {stringToHex} from 'viem';
type Provider={request:(args:{method:string;params?:unknown[]})=>Promise<unknown>;on?:(event:string,fn:()=>void)=>void;removeListener?:(event:string,fn:()=>void)=>void};
type Choice={id:string;name:string;provider:Provider};
type Link={address:string;chainId:number};
const chain='0xb626';
export default function Wallet({signedIn,signInUrl}:{signedIn:boolean;signInUrl:string}){
 const [open,setOpen]=useState(false),[providers,setProviders]=useState<Choice[]>([]),[link,setLink]=useState<Link|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[loaded,setLoaded]=useState(!signedIn);
 const selected=useRef<Provider|null>(null),changed=useRef(0),locked=useRef(false);
 async function api(input?:Record<string,unknown>){const r=await fetch('/api/wallet',input?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}:{cache:'no-store'});const data=await r.json() as {error?:string;wallet:Link|null;nonce:string;message:string};if(!r.ok)throw Error(data.error||'Wallet request failed');return data}
 async function reload(){try{const data=await api();setLink(data.wallet);setLoaded(true)}catch(e){setMessage((e as Error).message)}}
 useEffect(()=>{if(signedIn)void reload();const announce=(e:Event)=>{const d=(e as CustomEvent).detail;if(!d?.provider?.request||typeof d.info?.uuid!=='string')return;setProviders(old=>old.some(p=>p.id===d.info.uuid)?old:[...old,{id:d.info.uuid,name:String(d.info.name).slice(0,60),provider:d.provider}])};window.addEventListener('eip6963:announceProvider',announce);window.dispatchEvent(new Event('eip6963:requestProvider'));const injected=(window as unknown as {ethereum?:Provider}).ethereum;if(injected)setProviders(old=>old.length?old:[{id:'injected',name:'Browser wallet',provider:injected}]);return()=>window.removeEventListener('eip6963:announceProvider',announce)},[signedIn]);
 useEffect(()=>{const p=selected.current;if(!p)return;const onChange=()=>{changed.current++;setMessage('Wallet account or network changed. Your saved link stays unchanged; reconnect to verify the new selection.')};p.on?.('accountsChanged',onChange);p.on?.('chainChanged',onChange);p.on?.('disconnect',onChange);return()=>{p.removeListener?.('accountsChanged',onChange);p.removeListener?.('chainChanged',onChange);p.removeListener?.('disconnect',onChange)}},[busy]);
 async function connect(p:Provider){if(locked.current||!signedIn)return;locked.current=true;selected.current=p;setBusy(true);setMessage('Approve the connection in your wallet.');try{
 const accounts=await p.request({method:'eth_requestAccounts'}) as string[];if(!accounts[0])throw Error('No wallet account selected.');const address=accounts[0];
 if(await p.request({method:'eth_chainId'})!==chain){setMessage('Switch to Robinhood Chain testnet in your wallet.');try{await p.request({method:'wallet_switchEthereumChain',params:[{chainId:chain}]})}catch(e){if((e as {code?:number}).code!==4902)throw e;await p.request({method:'wallet_addEthereumChain',params:[{chainId:chain,chainName:'Robinhood Chain Testnet',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:['https://rpc.testnet.chain.robinhood.com'],blockExplorerUrls:['https://explorer.testnet.chain.robinhood.com']}]});await p.request({method:'wallet_switchEthereumChain',params:[{chainId:chain}]})}}
 if(await p.request({method:'eth_chainId'})!==chain)throw Error('Please select Robinhood Chain testnet.');
 const revision=changed.current;const c=await api({action:'challenge',address});setMessage('Sign the wallet-link message. This costs no gas.');const signature=await p.request({method:'personal_sign',params:[stringToHex(c.message),address]});const current=await p.request({method:'eth_accounts'}) as string[];
 if(changed.current!==revision||current[0]?.toLowerCase()!==address.toLowerCase()||await p.request({method:'eth_chainId'})!==chain)throw Error('Account or network changed. Please connect again.');
 const data=await api({action:'verify',nonce:c.nonce,signature});setLink(data.wallet);setLoaded(true);setMessage('Wallet verified and linked to your cloud profile.');
 }catch(e){const code=(e as {code?:number}).code;setMessage(code===4001?'Request cancelled. Your saved wallet link has not changed.':code===-32002?'A wallet request is already open. Check your wallet.':(e as Error).message||'Wallet connection failed. Try again.')}finally{locked.current=false;setBusy(false)}}
 async function unlink(){if(locked.current)return;locked.current=true;setBusy(true);try{await api({action:'unlink'});setLink(null);setMessage('Wallet unlinked from your profile.');selected.current=null}catch(e){setMessage((e as Error).message)}finally{locked.current=false;setBusy(false)}}
 return <div className="wallet-area"><button className="wallet-toggle" onClick={()=>setOpen(!open)} aria-expanded={open}>{link?`WALLET LINKED · ${link.address.slice(0,6)}…${link.address.slice(-4)}`:'CONNECT WALLET'} <span>↗</span></button>{open&&<section className="wallet-panel" aria-label="Connect wallet"><h2>Robinhood Chain <span>TESTNET</span></h2><p>Link a standard EVM wallet to your game account. SMASH tokens and NFTs are not live yet.</p>{!signedIn?<a href={signInUrl} target="_top">Sign in with ChatGPT to link your wallet →</a>:<>{link&&<div className="linked-wallet"><span>Verified profile address</span><a href={`https://explorer.testnet.chain.robinhood.com/address/${link.address}`} target="_blank" rel="noreferrer">{link.address}</a><button onClick={unlink} disabled={busy}>Unlink from profile</button></div>}{!loaded&&<button disabled={busy} onClick={()=>void reload()}>Retry loading wallet link</button>}{providers.length?providers.map(p=><button key={p.id} disabled={busy||!loaded} onClick={()=>void connect(p.provider)}>{busy?'CHECK YOUR WALLET…':`${link?'RELINK WITH':'CONNECT'} ${p.name.toUpperCase()}`}</button>):<p className="wallet-help">No wallet detected in this browser. Open this game in your wallet’s built-in browser, or use a desktop browser with an EVM wallet extension. QR / WalletConnect pairing is not available yet.</p>}</>}<p className="wallet-status" role="status">{message||'A signature verifies ownership. No payment or token approval is requested.'}</p></section>}</div>
}
